# Generated by Django 6.0.4 on 2026-05-06 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeentry',
            name='component',
            field=models.CharField(choices=[('attendance', 'Attendance (10%)'), ('participation', 'Participation (10%)'), ('quiz', 'Quizzes (20%)'), ('assignment', 'Assignments (20%)'), ('midterm_exam', 'Midterm Exam (20%)'), ('final_exam', 'Final Exam (20%)'), ('project_work', 'Project Work (Custom %)')], default='quiz', help_text='CHED grading component', max_length=20),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='component_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this component (e.g., 20 means 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grading_structure',
            field=models.CharField(choices=[('semester', 'Semester (2 terms per year)'), ('trimester', 'Trimester (3 terms per year)')], default='semester', help_text="Select your school's academic calendar structure", max_length=20),
        ),
    ]
