# Generated by Django 6.0.4 on 2026-05-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTrack', '0002_gradeentry_component_gradeentry_component_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='grading_period',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('endterm', 'Endterm'), ('project', 'Project')], max_length=20),
        ),
    ]
