# Generated by Django 6.0.4 on 2026-05-06 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTrack', '0003_alter_gradeentry_grading_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='component',
            field=models.CharField(blank=True, choices=[('attendance', 'Attendance (10%)'), ('participation', 'Participation (10%)'), ('quiz', 'Quizzes (20%)'), ('assignment', 'Assignments (20%)'), ('midterm_exam', 'Midterm Exam (20%)'), ('final_exam', 'Final Exam (20%)'), ('project_work', 'Project Work (Custom %)')], default='quiz', help_text='CHED grading component (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='component_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Weight of this component (optional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
